name: UHCReloaded-MEtcdPatch
version: 1.19.08-SNAPSHOT
main: cat.kiwi.minecraft.metcd.uhcreloaded.patch.UHCPatch
load: STARTUP
authors: [ moeKiwiSAMA ]
description: Patch for uhcreloaded
depends: [ UHCReloaded ]
api-version: 1.16